language: node_js
node_js:
  - "11.10"

stages:
  -test
  -publish

jobs:
  include:
    -stage: test
    -script: npm test

deploy:
  provider: npm
  email: "$MY_EMAIL"
  api_key: "$NPM_KEY"
  skip_cleanup: true
  on:
    tags: true
